services:
  - type: web
    name: sharesphere-app
    runtime: docker
    plan: free
    envVars:
      - key: DB_URL
        value: "jdbc:postgresql://ep-soft-sunset-am6a2oz3-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require"
      - key: DB_USER
        value: "neondb_owner"
      - key: DB_PASSWORD
        sync: false # Set this in Render dashboard

